house_pratice2<-read.csv("C:/Users/asif/Downloads/house (1).csv",header=T)
dim(house_pratice2)
str(house_pratice2)
house_pratice2$id<-NULL
house_pratice2$date<-NULL
house_pratice2$zipcode<-NULL
boxplot(house_pratice2$price)
IQR(house_pratice2$price)*1.5+645000
house_p<-subset(house_pratice2,house_pratice2$price<=1129575)
boxplot(house_p$price)
vect3<-c("floors","waterfront","view","condition","grade")
house_p[,vect3]<-lapply(house_p[,vect3],factor)
str(house_p)
house_p$yr_built<-2015-house_p$yr_built
house_p$yr_renovated[house_p$yr_renovated==0]<-2015
house_p$yr_renovated<-2015-house_p$yr_renovated
index3<-createDataPartition(house_p$price,p=0.7,list=F)
training_pratice<-house_p[index3,]
testing_pratice<-house_p[-index3,]
head(training_pratice)
head(testing_pratice)
house_pratice_model<-lm(price~.,data=training_pratice)
summary(house_pratice_model)
na.omit(house_p)
training_pratice$pred_pratice<-predict(house_pratice_model)
training_pratice$res<-residuals(house_pratice_model)
rmsetrain<-sqrt(mean(training_pratice$res^2))
rmsetrain
summary(testing_pratice$bedrooms)
testing_pratice$pred<-predict(house_pratice_model,testing_pratice)
testing_pratice2<-subset(testing_pratice,testing_pratice$bedrooms!=1)
testing_pratice$res<-testing_pratice$price-testing_pratice$pred
rmsetest<-sqrt(mean(testing_pratice$res^2))
rmsetest
library(car)
library(carData)
vif(house_pratice_model)
